"""empty message

Revision ID: 05a82aca7bf5
Revises: 32a478ba3a0b
Create Date: 2023-06-02 23:21:21.593918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a82aca7bf5'
down_revision = '32a478ba3a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('name_movie', sa.String(length=120), nullable=False),
    sa.Column('relase_date', sa.String(length=80), nullable=False),
    sa.Column('director', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('movie_id'),
    sa.UniqueConstraint('name_movie')
    )
    op.create_table('people',
    sa.Column('characeteres_id', sa.Integer(), nullable=False),
    sa.Column('name_people', sa.String(length=120), nullable=False),
    sa.Column('height', sa.String(length=80), nullable=False),
    sa.Column('color_eyes', sa.String(length=80), nullable=False),
    sa.Column('age', sa.String(length=80), nullable=False),
    sa.Column('born_date', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('characeteres_id'),
    sa.UniqueConstraint('name_people')
    )
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_planet', sa.String(length=120), nullable=False))
        batch_op.alter_column('climate',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.drop_constraint('planet_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['name_planet'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('planet_name_key', ['name'])
        batch_op.alter_column('climate',
               existing_type=sa.String(length=80),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
        batch_op.drop_column('name_planet')

    op.drop_table('people')
    op.drop_table('movie')
    # ### end Alembic commands ###
