"""empty message

Revision ID: 2b366aa442fe
Revises: 09f0247d0b6b
Create Date: 2023-06-06 16:55:37.947981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b366aa442fe'
down_revision = '09f0247d0b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peoples',
    sa.Column('characeteres_id', sa.Integer(), nullable=False),
    sa.Column('name_people', sa.String(length=120), nullable=False),
    sa.Column('age', sa.String(length=80), nullable=False),
    sa.Column('born_date', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('characeteres_id'),
    sa.UniqueConstraint('name_people')
    )
    op.drop_table('people')
    op.drop_table('favorite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('people_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['people_id'], ['people.characeteres_id'], name='favorite_people_id_fkey'),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.planet_id'], name='favorite_planet_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite_user_id_fkey')
    )
    op.create_table('people',
    sa.Column('characeteres_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name_people', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('age', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('born_date', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('characeteres_id', name='people_pkey'),
    sa.UniqueConstraint('name_people', name='people_name_people_key')
    )
    op.drop_table('peoples')
    # ### end Alembic commands ###
