"""empty message

Revision ID: ce10296491ba
Revises: 05a82aca7bf5
Create Date: 2023-06-03 01:57:38.709634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce10296491ba'
down_revision = '05a82aca7bf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('movie_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name_movie', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('relase_date', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('director', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('movie_id', name='movie_pkey'),
    sa.UniqueConstraint('name_movie', name='movie_name_movie_key')
    )
    # ### end Alembic commands ###
